export const ALL_DEPARTMENTS = [
  "DEVELOPMENT",
  "INFRASTRUCTURE_DEVOPS",
  "CONSULTING",
  "TECHNICAL_SUPPORT",
  "QUALITY_ASSURANCE",
  "HUMAN_RESOURCES",
  "FINANCE_ACCOUNTING",
  "SALES",
  "MARKETING",
  "EXECUTIVE_MANAGEMENT",
] as const;

export type Department = (typeof ALL_DEPARTMENTS)[number];
